name: than_pdf_engine_example
description: "Demonstrates how to use the than_pdf_engine package."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.0
dependencies:
  flutter:
    sdk: flutter

  than_pdf_engine:
    # path: ../
    git: https://github.com/ThanCoder/than_pdf_engine.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  than_pkg: ^5.1.0
  t_widgets: ^2.6.1
  pdfium_dart: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
