name: than_pdf_engine
description: "than_pdf_engine -> dart package.wrapper cpp langage.pdfium + stb_image_write ."
version: 0.5.0
repository: https://github.com/ThanCoder/than_pdf_engine.git


platforms:
  android:
  linux:

environment:
  sdk: ^3.12.0

dependencies:
  code_assets: ^1.0.0
  hooks: ^1.0.0
  logging: ^1.3.0
  ffi: ^2.1.4
  
dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0
