name: than_pdf_engine
description: "than_pdf_engine -> dart package.wrapper cpp langage.pdfium + stb_image_write ."
version: 1.0.0
repository: https://github.com/ThanCoder/than_pdf_engine.git


# platforms:
#   android:
#   linux:

environment:
  sdk: ^3.12.0

dependencies:
  ffi: ^2.1.4
  image: ^4.9.1
  pdfium_dart: ^0.2.5
  
dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0
